fix: typo
OtusGolang/final_project pull request #1
Opened 2022-04-01 23:43 UTC by sshaplygin

2022-04-02 04:12 UTC, Antonboom requested changes

2022-04-02 04:12 UTC, Antonboom commented on 01-anti-bruteforce.md
> -* Тесты адекватны и полностью покрывают фукнционал - 1 балл.
мб поправим везде на функциональность? :)

чтобы QA инженеры палками не били

2022-04-02 04:12 UTC, Antonboom commented on 05-system-stats-daemon.md
> +# ТЗ демона, осуществляющий "Системный мониторинг"
теперь причастие не в той форме

мб "ТЗ на разработку демона, осуществляющего ..."?

2022-04-02 04:12 UTC, Antonboom commented on 05-system-stats-daemon.md
> +Сбор информации, её парсинг и пр. должен осуществляется как можно более конкурентно.
глагол не в той форме

2022-04-03 07:36 UTC, Antonboom requested changes

2022-04-03 07:36 UTC, Antonboom commented on 05-system-stats-daemon.md
> +Сбор информации, её парсинг и пр. должен осуществлять как можно более конкурентно.
`должен осуществлять` а кто должен?

может `сбор <...> должен осуществляться?`?

2022-04-04 11:24 UTC, sshaplygin commented on 05-system-stats-daemon.md
> +Сбор информации, её парсинг и пр. должен осуществлять как можно более конкурентно.
блэт, спасибо

2022-04-06 04:01 UTC, Antonboom approved these changes

2022-04-06 04:01 UTC, merged